# Stage 1: Build the NestJS app
FROM node:19 AS build

# Set the working directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the app
RUN npm run build

# Stage 2: Run the NestJS app
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy the build output to the working directory
COPY --from=build /app/dist ./dist

# Expose the port the app runs on
EXPOSE 5252

# Start the server
CMD ["node", "dist/main"]
